//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bayu.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel
    {
        public string NomorID { get; set; }
        public string Nama { get; set; }
        public string TempatTanggalLahir { get; set; }
        public string Alamat { get; set; }
        public string Email { get; set; }
    }
}
